name: MIL
channels:
  - conda-forge
  - defaults
  - pytorch-nightly
dependencies:
  - hdf5=1.10.6
  - ipykernel=6.15.0
  - llvm-openmp=8.0.1
  - matplotlib=3.7.1
  - meson=1.0.1
  - python=3.9.16
  - scikit-image=0.19.3
  - scikit-learn=1.2.1
  - seaborn=0.12.2
  - tensorflow=2.10.0
  - torchaudio
  - torchvision
  - tqdm=4.64.1
  - xlrd=2.0.1
  - xlwt=1.3.0
  - pip:
      - aiohttp==3.8.3
      - blinker==1.4
      - Bottleneck==1.3.5
      - brotlipy==0.7.0
      - color-transfer==0.1
      - conda-env-export==0.4.5
      - dask==2023.4.1
      - gmpy2==2.1.2
      - imagecodecs==2021.8.26
      - mkl-fft==1.3.1
      - mkl-random==1.2.2
      - mkl-service==2.4.0
      - munkres==1.1.4
      - numexpr==2.8.4
      - opencv-python==4.7.0.72
      - openslide-python==1.2.0
      - pip==23.0.1
      - pooch==1.4.0
      - PyJWT==2.4.0
      - pyOpenSSL==23.0.0
      - PyQt5-sip==12.11.0
      - PySocks==1.7.1
      - roboticstoolbox-python==1.1.0
      - sip==6.6.2
      - tensorflow-gpu==2.5.0
      - torch-tb-profiler==0.4.1
      - transformers==4.29.2
      - triton==2.0.0
      - yolov4==2.0.3
